using UnityEngine;
using UnityEngine.SceneManagement;

namespace Lessons
{
    public class GameManager : MonoBehaviour
    {
        public static GameManager instance;

        private void Awake()
        {
            // make it a singelton
            if (instance == null)
                instance = this;
            else if (instance != this)
                // singleton: there can only ever be one instance of a GameManager.
                Destroy(gameObject);
        }

        // Start is called before the first frame update
        private void Start()
        {
        }

        // Update is called once per frame
        private void Update()
        {
        }

        public void RestartGame()
        {
            Debug.Log("Restart Game");
            SceneManager.LoadScene(SceneManager.GetActiveScene().buildIndex);
        }
    }
}